// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __RollingWindow_h__
#define __RollingWindow_h__

#include "RollingWindow_RcppExports.h"

#endif // __RollingWindow_h__
