// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RollingWindow.h"
#include <Rcpp.h>
#include <string>
#include <set>

using namespace Rcpp;

// NaSub
NumericMatrix NaSub(const SEXP& x, double repl, bool last_obs, int maxgap, bool leading);
static SEXP RollingWindow_NaSub_try(SEXP xSEXP, SEXP replSEXP, SEXP last_obsSEXP, SEXP maxgapSEXP, SEXP leadingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type repl(replSEXP);
    Rcpp::traits::input_parameter< bool >::type last_obs(last_obsSEXP);
    Rcpp::traits::input_parameter< int >::type maxgap(maxgapSEXP);
    Rcpp::traits::input_parameter< bool >::type leading(leadingSEXP);
    rcpp_result_gen = Rcpp::wrap(NaSub(x, repl, last_obs, maxgap, leading));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_NaSub(SEXP xSEXP, SEXP replSEXP, SEXP last_obsSEXP, SEXP maxgapSEXP, SEXP leadingSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_NaSub_try(xSEXP, replSEXP, last_obsSEXP, maxgapSEXP, leadingSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingBeta
NumericVector RollingBeta(const SEXP& x, const SEXP& y, int window, bool expanding, std::string na_method, bool pop);
static SEXP RollingWindow_RollingBeta_try(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingBeta(x, y, window, expanding, na_method, pop));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingBeta(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingBeta_try(xSEXP, ySEXP, windowSEXP, expandingSEXP, na_methodSEXP, popSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingCompound
NumericMatrix RollingCompound(const SEXP& x, int window, long double scale, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingCompound_try(SEXP xSEXP, SEXP windowSEXP, SEXP scaleSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< long double >::type scale(scaleSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingCompound(x, window, scale, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingCompound(SEXP xSEXP, SEXP windowSEXP, SEXP scaleSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingCompound_try(xSEXP, windowSEXP, scaleSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingCov
NumericVector RollingCov(const SEXP& x, const SEXP& y, int window, bool expanding, std::string na_method, bool pop);
static SEXP RollingWindow_RollingCov_try(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingCov(x, y, window, expanding, na_method, pop));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingCov(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingCov_try(xSEXP, ySEXP, windowSEXP, expandingSEXP, na_methodSEXP, popSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingCorr
NumericVector RollingCorr(const SEXP& x, const SEXP& y, int window, bool expanding, std::string na_method, bool pop);
static SEXP RollingWindow_RollingCorr_try(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingCorr(x, y, window, expanding, na_method, pop));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingCorr(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingCorr_try(xSEXP, ySEXP, windowSEXP, expandingSEXP, na_methodSEXP, popSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingKurt
NumericMatrix RollingKurt(const SEXP& x, int window, bool expanding, std::string na_method, bool pop);
static SEXP RollingWindow_RollingKurt_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingKurt(x, window, expanding, na_method, pop));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingKurt(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingKurt_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP, popSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingMax
NumericMatrix RollingMax(const SEXP& x, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingMax_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingMax(x, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingMax(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingMax_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingMean
NumericMatrix RollingMean(const SEXP& x, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingMean_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingMean(x, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingMean(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingMean_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingMAE
NumericVector RollingMAE(const SEXP& x, const SEXP& y, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingMAE_try(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingMAE(x, y, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingMAE(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingMAE_try(xSEXP, ySEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingMS
NumericVector RollingMS(const SEXP& x, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingMS_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingMS(x, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingMS(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingMS_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingMSE
NumericVector RollingMSE(const SEXP& x, const SEXP& y, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingMSE_try(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingMSE(x, y, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingMSE(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingMSE_try(xSEXP, ySEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingMedian
NumericMatrix RollingMedian(const SEXP& x, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingMedian_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingMedian(x, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingMedian(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingMedian_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingMin
NumericMatrix RollingMin(const SEXP& x, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingMin_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingMin(x, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingMin(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingMin_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingProd
NumericMatrix RollingProd(const SEXP& x, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingProd_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingProd(x, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingProd(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingProd_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingRMSE
NumericVector RollingRMSE(const SEXP& x, const SEXP& y, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingRMSE_try(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingRMSE(x, y, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingRMSE(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingRMSE_try(xSEXP, ySEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingSkew
NumericMatrix RollingSkew(const SEXP& x, int window, bool expanding, std::string na_method, bool pop);
static SEXP RollingWindow_RollingSkew_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingSkew(x, window, expanding, na_method, pop));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingSkew(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingSkew_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP, popSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingStd
NumericMatrix RollingStd(const SEXP& x, int window, bool expanding, std::string na_method, bool pop);
static SEXP RollingWindow_RollingStd_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingStd(x, window, expanding, na_method, pop));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingStd(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingStd_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP, popSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingSum
NumericMatrix RollingSum(const SEXP& x, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingSum_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingSum(x, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingSum(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingSum_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingSumprod
NumericVector RollingSumprod(const SEXP& x, const SEXP& y, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingSumprod_try(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingSumprod(x, y, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingSumprod(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingSumprod_try(xSEXP, ySEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingSS
NumericVector RollingSS(const SEXP& x, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingSS_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingSS(x, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingSS(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingSS_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingSSE
NumericMatrix RollingSSE(const SEXP& x, const SEXP& y, int window, bool expanding, std::string na_method);
static SEXP RollingWindow_RollingSSE_try(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingSSE(x, y, window, expanding, na_method));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingSSE(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingSSE_try(xSEXP, ySEXP, windowSEXP, expandingSEXP, na_methodSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingVar
NumericMatrix RollingVar(const SEXP& x, int window, bool expanding, std::string na_method, bool pop);
static SEXP RollingWindow_RollingVar_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingVar(x, window, expanding, na_method, pop));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingVar(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingVar_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP, popSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingZscore
NumericMatrix RollingZscore(const SEXP& x, int window, bool expanding, std::string na_method, bool pop);
static SEXP RollingWindow_RollingZscore_try(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type pop(popSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingZscore(x, window, expanding, na_method, pop));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingZscore(SEXP xSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP popSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingZscore_try(xSEXP, windowSEXP, expandingSEXP, na_methodSEXP, popSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}
// RollingSharpe
NumericMatrix RollingSharpe(const SEXP& x, const SEXP& Rf, int window, bool expanding, std::string na_method, double scale);
static SEXP RollingWindow_RollingSharpe_try(SEXP xSEXP, SEXP RfSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< const SEXP& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const SEXP& >::type Rf(RfSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< bool >::type expanding(expandingSEXP);
    Rcpp::traits::input_parameter< std::string >::type na_method(na_methodSEXP);
    Rcpp::traits::input_parameter< double >::type scale(scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(RollingSharpe(x, Rf, window, expanding, na_method, scale));
    return rcpp_result_gen;
END_RCPP_RETURN_ERROR
}
RcppExport SEXP RollingWindow_RollingSharpe(SEXP xSEXP, SEXP RfSEXP, SEXP windowSEXP, SEXP expandingSEXP, SEXP na_methodSEXP, SEXP scaleSEXP) {
    SEXP rcpp_result_gen;
    {
        Rcpp::RNGScope rcpp_rngScope_gen;
        rcpp_result_gen = PROTECT(RollingWindow_RollingSharpe_try(xSEXP, RfSEXP, windowSEXP, expandingSEXP, na_methodSEXP, scaleSEXP));
    }
    Rboolean rcpp_isInterrupt_gen = Rf_inherits(rcpp_result_gen, "interrupted-error");
    if (rcpp_isInterrupt_gen) {
        UNPROTECT(1);
        Rf_onintr();
    }
    Rboolean rcpp_isError_gen = Rf_inherits(rcpp_result_gen, "try-error");
    if (rcpp_isError_gen) {
        SEXP rcpp_msgSEXP_gen = Rf_asChar(rcpp_result_gen);
        UNPROTECT(1);
        Rf_error(CHAR(rcpp_msgSEXP_gen));
    }
    UNPROTECT(1);
    return rcpp_result_gen;
}

// validate (ensure exported C++ functions exist before calling them)
static int RollingWindow_RcppExport_validate(const char* sig) { 
    static std::set<std::string> signatures;
    if (signatures.empty()) {
        signatures.insert("NumericMatrix(*NaSub)(const SEXP&,double,bool,int,bool)");
        signatures.insert("NumericVector(*RollingBeta)(const SEXP&,const SEXP&,int,bool,std::string,bool)");
        signatures.insert("NumericMatrix(*RollingCompound)(const SEXP&,int,long double,bool,std::string)");
        signatures.insert("NumericVector(*RollingCov)(const SEXP&,const SEXP&,int,bool,std::string,bool)");
        signatures.insert("NumericVector(*RollingCorr)(const SEXP&,const SEXP&,int,bool,std::string,bool)");
        signatures.insert("NumericMatrix(*RollingKurt)(const SEXP&,int,bool,std::string,bool)");
        signatures.insert("NumericMatrix(*RollingMax)(const SEXP&,int,bool,std::string)");
        signatures.insert("NumericMatrix(*RollingMean)(const SEXP&,int,bool,std::string)");
        signatures.insert("NumericVector(*RollingMAE)(const SEXP&,const SEXP&,int,bool,std::string)");
        signatures.insert("NumericVector(*RollingMS)(const SEXP&,int,bool,std::string)");
        signatures.insert("NumericVector(*RollingMSE)(const SEXP&,const SEXP&,int,bool,std::string)");
        signatures.insert("NumericMatrix(*RollingMedian)(const SEXP&,int,bool,std::string)");
        signatures.insert("NumericMatrix(*RollingMin)(const SEXP&,int,bool,std::string)");
        signatures.insert("NumericMatrix(*RollingProd)(const SEXP&,int,bool,std::string)");
        signatures.insert("NumericVector(*RollingRMSE)(const SEXP&,const SEXP&,int,bool,std::string)");
        signatures.insert("NumericMatrix(*RollingSkew)(const SEXP&,int,bool,std::string,bool)");
        signatures.insert("NumericMatrix(*RollingStd)(const SEXP&,int,bool,std::string,bool)");
        signatures.insert("NumericMatrix(*RollingSum)(const SEXP&,int,bool,std::string)");
        signatures.insert("NumericVector(*RollingSumprod)(const SEXP&,const SEXP&,int,bool,std::string)");
        signatures.insert("NumericVector(*RollingSS)(const SEXP&,int,bool,std::string)");
        signatures.insert("NumericMatrix(*RollingSSE)(const SEXP&,const SEXP&,int,bool,std::string)");
        signatures.insert("NumericMatrix(*RollingVar)(const SEXP&,int,bool,std::string,bool)");
        signatures.insert("NumericMatrix(*RollingZscore)(const SEXP&,int,bool,std::string,bool)");
        signatures.insert("NumericMatrix(*RollingSharpe)(const SEXP&,const SEXP&,int,bool,std::string,double)");
    }
    return signatures.find(sig) != signatures.end();
}

// registerCCallable (register entry points for exported C++ functions)
RcppExport SEXP RollingWindow_RcppExport_registerCCallable() { 
    R_RegisterCCallable("RollingWindow", "RollingWindow_NaSub", (DL_FUNC)RollingWindow_NaSub_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingBeta", (DL_FUNC)RollingWindow_RollingBeta_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingCompound", (DL_FUNC)RollingWindow_RollingCompound_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingCov", (DL_FUNC)RollingWindow_RollingCov_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingCorr", (DL_FUNC)RollingWindow_RollingCorr_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingKurt", (DL_FUNC)RollingWindow_RollingKurt_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingMax", (DL_FUNC)RollingWindow_RollingMax_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingMean", (DL_FUNC)RollingWindow_RollingMean_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingMAE", (DL_FUNC)RollingWindow_RollingMAE_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingMS", (DL_FUNC)RollingWindow_RollingMS_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingMSE", (DL_FUNC)RollingWindow_RollingMSE_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingMedian", (DL_FUNC)RollingWindow_RollingMedian_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingMin", (DL_FUNC)RollingWindow_RollingMin_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingProd", (DL_FUNC)RollingWindow_RollingProd_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingRMSE", (DL_FUNC)RollingWindow_RollingRMSE_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingSkew", (DL_FUNC)RollingWindow_RollingSkew_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingStd", (DL_FUNC)RollingWindow_RollingStd_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingSum", (DL_FUNC)RollingWindow_RollingSum_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingSumprod", (DL_FUNC)RollingWindow_RollingSumprod_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingSS", (DL_FUNC)RollingWindow_RollingSS_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingSSE", (DL_FUNC)RollingWindow_RollingSSE_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingVar", (DL_FUNC)RollingWindow_RollingVar_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingZscore", (DL_FUNC)RollingWindow_RollingZscore_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RollingSharpe", (DL_FUNC)RollingWindow_RollingSharpe_try);
    R_RegisterCCallable("RollingWindow", "RollingWindow_RcppExport_validate", (DL_FUNC)RollingWindow_RcppExport_validate);
    return R_NilValue;
}
