# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Replaces NAs with either the last non-NA observation, or a specified replacement value
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param repl The value used to replace NAs
#'@param last_obs TRUE if the last non-NA observation should be used instead of a specified replacement value
#'@param maxgap Runs of more than \code{maxgap} are retained. By default, the argument is set to 0, which 
#'will preserve all NAs. If set to -1, the argument is set to infinity such that sequences of any size of NAs
#'will be replaced with the last non-NA observation.
NaSub <- function(x, repl = 0, last_obs = TRUE, maxgap = 0L) {
    .Call('RollingWindow_NaSub', PACKAGE = 'RollingWindow', x, repl, last_obs, maxgap)
}

#'Estimates the coefficient (beta) from a univariate linear model y ~ x over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix; the independent variable
#'@param y A vector, matrix, list or other object coercible to a vector; the dependent variable
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic//'
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@param pop TRUE to calculate population (n) covariance, FALSE to calculate sample (n-1) covariance
#'@return A vector; rows 1 to (length(window) - 1) contain NAs.
#'@details Estimates \eqn{\hat{\beta_1}} from an ordinary least squares model \eqn{y = \beta_0 + \beta_1 x}.
#'Beta is defined as
#'\deqn{ \code{Beta} = \frac{cov(x, y)}{\sigma^2_x} }
#'where \eqn{cov} is covariance and \eqn{\sigma^2} is variance.
#'If input \code{x} contains more than one column, the rolling window calculation will be performed on each
#'column against the vector \code{y}. The dimensions of the return value will be the same as input \code{x}.
RollingBeta <- function(x, y, window, expanding = FALSE, na_rm = FALSE, pop = FALSE) {
    .Call('RollingWindow_RollingBeta', PACKAGE = 'RollingWindow', x, y, window, expanding, na_rm, pop)
}

#'Calculates simple compounding over a rolling window (e.g. of financial asset return series)
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param scale Used in the compounding exponent: product^(scale / window) - 1; any number (integer or floating point) may be used
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
#'@details Compounding a series of rates of return is defined as
#'\deqn{ \code{Compound} = \big(\prod^n_{i=1} (1+x_i)\big)^{scale / window} - 1 }
#'where \code{scale} is a parameter provided to (optionally) normalize the compounding to a desired period length;
#'this would commonly be used in a financial application where a return could be annualized by (e.g.) setting \code{scale}
#'to 252, 52, 12 or 4 if the time series is daily, weekly, monthly or quarterly, respectively, although any value for \code{scale}
#'may be used.
RollingCompound <- function(x, window, scale = 1.0, expanding = FALSE, na_rm = TRUE) {
    .Call('RollingWindow_RollingCompound', PACKAGE = 'RollingWindow', x, window, scale, expanding, na_rm)
}

#'Calculates covariance over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param y A vector, matrix, list or other object coercible to a vector
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@param pop TRUE to calculate population (n) covariance, FALSE to calculate sample (n-1) covariance
#'@return A vector; rows 1 to (length(window) - 1) contain NAs.
#'@details Sample covariance (see parameter \code{pop}) is defined as
#'\deqn{ \code{Cov} = \frac{1}{n-1} \sum^n_{i=1} (x_i - \bar{x})(y_i - \bar{y}) }
RollingCov <- function(x, y, window, expanding = FALSE, na_rm = FALSE, pop = FALSE) {
    .Call('RollingWindow_RollingCov', PACKAGE = 'RollingWindow', x, y, window, expanding, na_rm, pop)
}

#'Calculates Pearson correlation over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param y A vector, matrix, list or other object coercible to a vector
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@param pop TRUE to calculate population (n) std. deviation, FALSE to calculate sample (n-1) std. deviation
#'determines the starting number of observations used to calculate the statistic
#'@return A vector; rows 1 to (length(window) - 1) contain NAs.
#'@details Correlation is defined as
#'\deqn{ \code{Corr} = \frac{cov(x, y)}{\sigma_x\sigma_y} }
#'where \eqn{cov} is the covariance and \eqn{\sigma} is the standard deviation
RollingCorr <- function(x, y, window, expanding = FALSE, na_rm = FALSE, pop = FALSE) {
    .Call('RollingWindow_RollingCorr', PACKAGE = 'RollingWindow', x, y, window, expanding, na_rm, pop)
}

#'Calculates the excess kurtosis over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@param pop TRUE to calculate population (n) statistic, FALSE to calculate sample (n-1) statistic
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
#'@details Population excess skewness (see parameter \code{pop}) is defined as
#'\deqn{ \code{Kurt} = \frac{\frac{1}{n}\sum^n_{i=1}(x_i-\bar{x})^4}{\big(\frac{1}{n}\sum^n_{i=1}(x_i-\bar{x})^2\big)^2} - 3}
#'Sample excess kurtosis (see parameter \code{pop}) is defined as
#'\deqn{ \code{Kurt} = \frac{n(n+1)}{(n-1)(n-2)(n-3)}\frac{\sum^n_{i=1}(x_i-\bar{x})^4}{\big(\sum^n_{i=1}(x_i-\bar{x})^2\big)^2} -3 \frac{(n-1)^2}{(n-2)(n-3)} }
RollingKurt <- function(x, window, expanding = FALSE, na_rm = FALSE, pop = FALSE) {
    .Call('RollingWindow_RollingKurt', PACKAGE = 'RollingWindow', x, window, expanding, na_rm, pop)
}

#'Calculates the maximum over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
RollingMax <- function(x, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingMax', PACKAGE = 'RollingWindow', x, window, expanding, na_rm)
}

#'Calculates the arithmetic mean over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
#'@details The arithmetic mean is defined as
#'\deqn{\code{Mean} = \frac{1}{n}\sum^n_{i=1} x_i}
RollingMean <- function(x, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingMean', PACKAGE = 'RollingWindow', x, window, expanding, na_rm)
}

#'Calculates the mean absolute error over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param y A vector, matrix, list or other object coercible to a vector
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A vector; rows 1 to (length(window) - 1) contain NAs.
#'@details Mean absolute error is defined as
#'\deqn{ \code{MAE} = \frac{1}{n}\sum^n_{i=1}|x_i - y_i| }
#'where \eqn{x} and \eqn{y} represent the predicted and actual (true) values.
RollingMAE <- function(x, y, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingMAE', PACKAGE = 'RollingWindow', x, y, window, expanding, na_rm)
}

#'Calculates the mean of squares over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A vector; rows 1 to (length(window) - 1) contain NAs.
#'@details Mean of squares is defined as
#'\deqn{ \code{MS} = \frac{1}{n}\sum^n_{i=1} x^2_i }
RollingMS <- function(x, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingMS', PACKAGE = 'RollingWindow', x, window, expanding, na_rm)
}

#'Calculates the mean squared error over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param y A vector or single-column matrix; the error to be subtracted from x
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A vector; rows 1 to (length(window) - 1) contain NAs.
#'@details Mean squared error is defined as
#'\deqn{ \code{MSE} = \frac{1}{n}\sum^n_{i=1}(x_i - y_i)^2 }
#'where \eqn{x} and \eqn{y} represent the predicted and actual (true) values.
RollingMSE <- function(x, y, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingMSE', PACKAGE = 'RollingWindow', x, y, window, expanding, na_rm)
}

#'Calculates the median over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
#'@details If input \code{x} contains more than one column, the rolling window calculation will be performed on each
#'column. The dimensions of the return value will be the same as input \code{x}.
RollingMedian <- function(x, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingMedian', PACKAGE = 'RollingWindow', x, window, expanding, na_rm)
}

#'Calculates the minimum over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
#'@details If input \code{x} contains more than one column, the rolling window calculation will be performed on each
#'column. The dimensions of the return value will be the same as input \code{x}.
RollingMin <- function(x, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingMin', PACKAGE = 'RollingWindow', x, window, expanding, na_rm)
}

#'Calculates the product over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
#'@details Product is defined as
#'\deqn{ \code{Prod} = \prod^n_{i=1} x_i }
RollingProd <- function(x, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingProd', PACKAGE = 'RollingWindow', x, window, expanding, na_rm)
}

#'Calculates the root mean squared error over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param y A vector, matrix, list or other object coercible to a vector; the error to be subtracted from x
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A vector; rows 1 to (length(window) - 1) contain NAs.
#'@details Root mean squared error is defined as
#'\deqn{ \code{RMSE} = \sqrt{\frac{1}{n}\sum^n_{i=1}(x_i - y_i)^2 } }
#'where \eqn{x} and \eqn{y} represent the predicted and actual (true) values.
RollingRMSE <- function(x, y, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingRMSE', PACKAGE = 'RollingWindow', x, y, window, expanding, na_rm)
}

#'Calculates the skewness over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@param pop TRUE to calculate population (n) statistic, FALSE to calculate sample (n-1) statistic
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
#'@details Population skewness (see parameter \code{pop}) is defined as
#'\deqn{ \code{Skew} = \sqrt{n}\frac{\sum^n_{i=1}(x_i-\bar{x})^3}{\big(\sum^n_{i=1}(x_i-\bar{x})^2\big)^{3/2}}}
#'Sample skewness (see parameter \code{pop}) is defined as
#'\deqn{ \code{Skew} = \frac{n\sqrt{n-1}}{n-2}\frac{\sum^n_{i=1}(x_i-\bar{x})^3}{\big(\sum^n_{i=1}(x_i-\bar{x})^2\big)^{3/2}}}
RollingSkew <- function(x, window, expanding = FALSE, na_rm = FALSE, pop = FALSE) {
    .Call('RollingWindow_RollingSkew', PACKAGE = 'RollingWindow', x, window, expanding, na_rm, pop)
}

#'Calculates the standard deviation over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@param pop TRUE to calculate population (n) statistic, FALSE to calculate sample (n-1) statistic
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
#'@details Sample standard deviation (see parameter \code{pop}) is defined as
#'\deqn{ \code{Std} = \sqrt{\frac{1}{n-1}\sum^n_{i=1}(x_i - \bar{x})^2} }
RollingStd <- function(x, window, expanding = FALSE, na_rm = FALSE, pop = FALSE) {
    .Call('RollingWindow_RollingStd', PACKAGE = 'RollingWindow', x, window, expanding, na_rm, pop)
}

#'Calculates the sum over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
#'@details Sum is defined as
#'\deqn{ \code{Sum} = \sum^n_{i=1} x_i }
RollingSum <- function(x, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingSum', PACKAGE = 'RollingWindow', x, window, expanding, na_rm)
}

#'Calculates the sum product (dot product) over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param y A vector, matrix, list or other object coercible to a vector
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A vector; rows 1 to (length(window) - 1) contain NAs.
#'@details Sum product is defined as
#'\deqn{ \code{Sumprod} = \sum^n_{i=1} x_i y_i }
RollingSumprod <- function(x, y, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingSumprod', PACKAGE = 'RollingWindow', x, y, window, expanding, na_rm)
}

#'Calculates the sum of squares over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A vector; rows 1 to (length(window) - 1) contain NAs.
#'@details Sum of squares is defined as
#'\deqn{ \code{SS} = \sum^n_{i=1} x^2_i }
RollingSS <- function(x, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingSS', PACKAGE = 'RollingWindow', x, window, expanding, na_rm)
}

#'Calculates the sum of squared errors over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param y A vector, matrix, list or other object coercible to a vector; the error to be subtracted from x
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@return A vector; rows 1 to (length(window) - 1) contain NAs.
#'@details Sum of squared errors is defined as
#'\deqn{ \code{SSE} = \sum^n_{i=1}(x_i - y_i)^2 }
#'where \eqn{x} and \eqn{y} represent the predicted and actual (true) values.
RollingSSE <- function(x, y, window, expanding = FALSE, na_rm = FALSE) {
    .Call('RollingWindow_RollingSSE', PACKAGE = 'RollingWindow', x, y, window, expanding, na_rm)
}

#'Calculates the variance over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@param pop TRUE to calculate population (n) statistic, FALSE to calculate sample (n-1) statistic
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
#'@details Sample variance (see parameter \code{pop}) is defined as
#'\deqn{ \code{Var} = \frac{1}{n-1}\sum^n_{i=1}(x_i - \bar{x})^2 }
RollingVar <- function(x, window, expanding = FALSE, na_rm = FALSE, pop = FALSE) {
    .Call('RollingWindow_RollingVar', PACKAGE = 'RollingWindow', x, window, expanding, na_rm, pop)
}

#'Calculates the z-score (standardized value) over a rolling window
#'
#'@param x A vector, matrix, list or other object coercible to a matrix
#'@param window The size of the rolling window
#'@param expanding TRUE to calculate an expanding window instead of a rolling window; if TRUE, window
#'determines the starting number of observations used to calculate the statistic
#'@param na_rm TRUE to handle NAs (see notes on NA handling)
#'@param pop TRUE to calculate population (n) standard deviation, FALSE to calculate sample (n-1) standard deviation
#'@return A matrix; rows 1 to (length(window) - 1) contain NAs.
#'@details z-score is defined as
#'\deqn{ \code{Zscore} = \frac{x - \bar{x}}{\sigma} }
#'where \eqn{\sigma} is the standard deviation of x.
RollingZscore <- function(x, window, expanding = FALSE, na_rm = FALSE, pop = FALSE) {
    .Call('RollingWindow_RollingZscore', PACKAGE = 'RollingWindow', x, window, expanding, na_rm, pop)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('RollingWindow_RcppExport_registerCCallable', PACKAGE = 'RollingWindow')
})
